Repository ocadotechnology/aimmo-unity, pull requests merged in 2018-03, with the labels that each got.

#195 There was a minus that should be a plus
  UnityProject/Assets/Scripts/Camera/MoveCamera.cs
Labels: bug

#203 Minor Test Fixes. Closes #201 and #202
  UnityProject/Assets/Editor/Tests/OverlayGeneratorTests.cs
  UnityProject/Assets/Editor/Tests/PlayerGeneratorTest.cs
Labels: Development, bug, low priority, tests

#200 Add compass to the game, resolves #198
  README.md
  UnityProject/Assets/Editor/Tests/CanvasTests.cs
  UnityProject/Assets/Editor/Tests/CanvasTests.cs.meta
  UnityProject/Assets/Resources/Images/compass.png
  UnityProject/Assets/Resources/Images/compass.png.meta
  UnityProject/Assets/Scenes/Main.unity
  UnityProject/Assets/Scripts/Camera/MoveCamera.cs
  UnityProject/Assets/Scripts/Generators/LevelGenerator.cs
Labels: Development, UX/UI
